// this file is auto-generated by raptor, do not edit directly
function getTestConfig() {
    return {"browser": "firefox",
            "cs_port": "60751",
            "test_name": "raptor-sunspider-firefox",
            "test_settings_url": "http://127.0.0.1:60751/json/raptor-sunspider-firefox.json",
            "post_startup_delay": "30000",
            "benchmark_port": "37485",
            "host": "127.0.0.1",
            "debug_mode": "0",
            "browser_cycle": "1"};
}

